server:
  port: 18080

spring:
  application:
    name: spring-ai-alibaba-openmanus
  ai:
    openai:
      base-url: https://api.siliconflow.cn
      api-key:  xxx
#      base-url: http://localhost:11434
#      api-key: "ollama"
      chat:
        options:
          model: deepseek-ai/DeepSeek-R1
    #          model: qwq:32b
    mcp:
      client:
        request-timeout: 60000
        stdio:
          servers-configuration: classpath:/mcp-servers-config.json

manus:
  browser:
    headless: false # 设置为 true 则启用无头模式
